version: '3.9'

x-airflow-common:
  &airflow-common
  image: apache/airflow:2.8.1
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
    AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
    OBJECT_PREFIX: ${OBJECT_PREFIX}
    OCI_BUCKET_NAME: ${OCI_BUCKET_NAME}
    OCI_PROFILE: ${OCI_PROFILE}
    OCI_TENANCY: ${OCI_TENANCY}
    OCI_USER: ${OCI_USER}
    OCI_FINGERPRINT: ${OCI_FINGERPRINT}
    OCI_PRIVATE_KEY_PATH: ${OCI_PRIVATE_KEY_PATH}
    OCI_PASSPHRASE: ${OCI_PASSPHRASE}
    OCI_NAMESPACE: ${OCI_NAMESPACE}
    FILE_PATH: ${FILE_PATH}
    compartment_id: ${compartment_id}
    db_display_name: ${db_display_name}
    db_name: ${db_name}
    cpu_core_count: ${cpu_core_count}
    data_storage_size_in_tbs: ${data_storage_size_in_tbs}
    adb_admin_password: ${adb_admin_password}
    adb_wallet_password: ${adb_wallet_password}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    AIRFLOW__WEBSERVER__RBAC: 'true'
    BASE_DIR: ${BASE_DIR}
    FILE_PATH_RAW: ${FILE_PATH_RAW}
    FILE_PATH_GOLD: ${FILE_PATH_GOLD}
    FILE_PATH_BRONZE: ${FILE_PATH_BRONZE}
    ORACLE_HOME: /opt/airflow/wallet
    TNS_ADMIN: /opt/airflow/wallet
    ORACLE_USER: admin
    ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    ORACLE_WALLET_PASSWORD: ${ORACLE_WALLET_PASSWORD}
    DATABRICKS_HOST: ${DATABRICKS_HOST}
    DATABRICKS_TOKEN: ${DATABRICKS_TOKEN}
    DATABRICKS_NOTEBOOK_PATH: ${DATABRICKS_NOTEBOOK_PATH}
    ADB_HOST: ${ADB_HOST}
    ADB_USER: ${ADB_USER}
    ADB_PASSWORD: ${ADB_PASSWORD}
    WALLET_PATH: ${WALLET_PATH}
    LD_LIBRARY_PATH: /usr/lib/oracle/21/client64/lib
    _PIP_ADDITIONAL_REQUIREMENTS: >-
      kagglehub>=0.1.0
      oci>=2.0.0
      oci-cli>=3.0.0
      cx_Oracle>=8.3.0
      oracledb>=1.0.0
      pandas>=2.0.0
      pyarrow>=14.0.1
      apache-airflow-providers-oracle>=3.0.0
      apache-airflow-providers-databricks>=6.10.0
    ORACLE_TNS: ${ORACLE_TNS}
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./infra/wallet:/opt/airflow/wallet:ro
    - ./infra/instantclient/instantclient_23_9:/opt/oracle/instantclient:ro
    - ./outputs.json:/opt/airflow/outputs.json
    - ./data:/opt/airflow/data 
    - ${USERPROFILE}/.oci:/home/airflow/.oci:ro
    - ./scripts:/opt/airflow/scripts
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    - postgres


services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    volumes:
      - ./airflow_cache:/home/airflow/.cache

  scheduler:
    <<: *airflow-common
    command: scheduler

  init:
    <<: *airflow-common
    command: >-
      bash -c "airflow db init && airflow users create \
      --username ${AIRFLOW_USER} \
      --password ${AIRFLOW_PASS} \
      --firstname Admin \
      --lastname User \
      --role Admin \
      --email admin@example.com && python /opt/airflow/scripts/create_or_update_connection.py"

volumes:
  postgres-db-volume:
